server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: dubbo-client
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    messageTimeout: 5
    sender:
      #向http发送trace信息
      type: web
  sleuth:
    sampler:
      percentage: 1